using Microsoft.EntityFrameworkCore.Infrastructure; using Microsoft.EntityFrameworkCore.Migrations;
namespace Trackly.Infrastructure.Persistence.Migrations;
[DbContext(typeof(TracklyDbContext))][Migration("20240622000000_InitialCreate")] public partial class InitialCreate : Migration { protected override void Up(MigrationBuilder m) { m.Sql("""
CREATE TABLE IF NOT EXISTS \"Sources\" (\"Id\" uuid PRIMARY KEY, \"Name\" text NOT NULL, \"BaseUrl\" text NOT NULL, \"SourceType\" text NOT NULL, \"IsActive\" boolean NOT NULL, \"CreatedAt\" timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS \"Products\" (\"Id\" uuid PRIMARY KEY, \"SourceId\" uuid NOT NULL REFERENCES \"Sources\"(\"Id\") ON DELETE CASCADE, \"Name\" text NOT NULL, \"ProductUrl\" text NOT NULL, \"ImageUrl\" text NULL, \"Category\" text NULL, \"CurrentPrice\" numeric(12,2) NOT NULL, \"Currency\" text NOT NULL, \"Availability\" text NULL, \"Rating\" text NULL, \"LastScrapedAt\" timestamp with time zone NULL, \"CreatedAt\" timestamp with time zone NOT NULL, \"UpdatedAt\" timestamp with time zone NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Products_SourceId_ProductUrl\" ON \"Products\" (\"SourceId\", \"ProductUrl\");
CREATE TABLE IF NOT EXISTS \"PriceHistories\" (\"Id\" uuid PRIMARY KEY, \"ProductId\" uuid NOT NULL REFERENCES \"Products\"(\"Id\") ON DELETE CASCADE, \"Price\" numeric(12,2) NOT NULL, \"Currency\" text NOT NULL, \"ScrapedAt\" timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS \"ScrapeJobs\" (\"Id\" uuid PRIMARY KEY, \"SourceId\" uuid NOT NULL REFERENCES \"Sources\"(\"Id\") ON DELETE CASCADE, \"Status\" text NOT NULL, \"StartedAt\" timestamp with time zone NULL, \"FinishedAt\" timestamp with time zone NULL, \"ProductsFound\" integer NOT NULL, \"ProductsUpdated\" integer NOT NULL, \"ErrorMessage\" text NULL);
INSERT INTO \"Sources\" VALUES ('11111111-1111-1111-1111-111111111111','Books to Scrape','https://books.toscrape.com','Product',true,'2024-01-01T00:00:00Z') ON CONFLICT DO NOTHING;
"""); } protected override void Down(MigrationBuilder m) { m.DropTable("PriceHistories");m.DropTable("ScrapeJobs");m.DropTable("Products");m.DropTable("Sources"); } }
